INSERT INTO blogful_articles ( title, content, date_published)
VALUES
    ('How to Train Your Dragon', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', now() - '20 days'::INTERVAL),
    ('How to Fly Fish', 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua', now() - '19 days'::INTERVAL), 
    ('How to See in the Dark', 'Ut enim ad minim veniam', now() - '18 days'::INTERVAL),  
    ('How to Create Your Own Universe', 'Quis nostrud exercitation ullamco laboris nisi', now() - '17 days'::INTERVAL), 
    ('How to Heal Anything With A Touch', 'Ut aliquip ex ea commodo consequat', now() - '16 days'::INTERVAL), 
    ('How to Commune With Nature', 'Duis aute irure dolor in reprehenderit in voluptate', now() - '15 days'::INTERVAL), 
    ('How to Cast Fireball', 'Velit esse cillum dolore eu fugiat nulla pariatur', now() - '14 days'::INTERVAL), 
    ('How to Inspire Others with Song', 'Excepteur sint occaecat cupidatat non proident', now() - '13 days'::INTERVAL), 
    ('How to Sneak Up on the Competition', 'Sunt in culpa qui officia', now() - '12 days'::INTERVAL), 
    ('How to Care for your Spider Companion', 'Deserunt mollit anim id est laborum', now() - '11 days'::INTERVAL), 
    ('How to Keep Your Friends from Death', 'Sed ut perspiciatis unde omnis iste natus error sit voluptatem', now() - '10 days'::INTERVAL), 
    ('How to Summon Eldritch Beings', 'Accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore', now() - '9 days'::INTERVAL), 
    ('How to Make a Deal with a Devil', 'Veritatis et quasi architecto beatae vitae dicta sunt explicabo', now() - '8 days'::INTERVAL), 
    ('How to Create Liquid Gold', 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur', now() - '7 days'::INTERVAL), 
    ('How to Grow Plants Anywhere', 'Aut odit aut fugit, sed quia consequuntur magni', now() - '6 days'::INTERVAL), 
    ('How to Use Your Rage', 'Dolores eos qui ratione voluptatem sequi nesciunt', now() - '5 days'::INTERVAL), 
    ('How to Avoid Making Killer Robots', 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet', now() - '4 days'::INTERVAL), 
    ('How to Make Your Own Friends with Necromancy', 'Fusce quis diam lacinia, mattis dolor sed, facilisis neque', now() - '3 days'::INTERVAL), 
    ('How to Trick Demons and Make Them Serve', 'Aenean et sapien pretium, placerat quam congue, vestibulum purus', now() - '2 days'::INTERVAL), 
    ('How to Tell If Your Friend is a Doppelganger', 'Curabitur non volutpat eros', now() - '1 days'::INTERVAL),
    ('How to Toss a Coin to your Monster Hunter', 'In maximus nulla sed est ultricies, eget pellentesque nibh malesuada', now());  
